FROM rasa/rasa-sdk:3.6.2

USER root

# Install system dependencies
RUN apt-get update -qq && \
    apt-get install -y --no-install-recommends \
    python3-dev \
    default-libmysqlclient-dev \
    build-essential \
    unixodbc \
    unixodbc-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements first to leverage Docker cache
COPY requirements.actions.txt /app/requirements.actions.txt
RUN pip install --no-cache-dir -r /app/requirements.actions.txt

# Copy actions code
COPY actions /app/actions
COPY data /app/data

USER 1001

CMD ["start", "--actions", "actions"]