version: '3.8'

services:
  rasa:
    build: .
    volumes:
      - ./:/app
    ports:
      - "5005:5005"
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3307
      - MYSQL_USER=root
      - MYSQL_PASSWORD=adieadie
      - MYSQL_DATABASE=PGDEPGDE
    command: >
      rasa run -m models --enable-api --cors "*" --debug
    depends_on:
      - action-server
    extra_hosts:
      - "host.docker.internal:host-gateway"

  action-server:
    build: 
      context: .
      dockerfile: Dockerfile.actions
    volumes:
      - ./actions:/app/actions
      - ./data:/app/data
    ports:
      - "5055:5055"
    environment:
      - PYTHONPATH=/app
      - MYSQL_HOST=host.docker.internal
      - MYSQL_PORT=3307
      - MYSQL_USER=root
      - MYSQL_PASSWORD=adieadie
      - MYSQL_DATABASE=PGDEPGDE
    command: ["start", "--actions", "actions"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
